dist: trusty
language: node_js
node_js:
  - '14.14'

addons:
  chrome: stable

before_script:
- npm install
- npx ng build

script: 
- npm install codecov -g
- xvfb-run npm test

after_success:
  - codecov
