name: CI

on: [push]

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          npm ci
          npm test

  testbuild:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Build
        run: |
          npm ci
          npm run build --configuration=essprod

  gitlab:
    name: Build and deploy
    needs: [unittest, testbuild]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ESS pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: 3367
          ref: "master"
          host: "https://gitlab.esss.lu.se"
          debug: true

      - name: Trigger  MAXIV pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.MAXIV_TOKEN }}
          project_id: 22690704
          ref: "master"
          host: "https://gitlab.com"
          debug: true
