name: Test

on: [push, pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: |
          npm ci
          npx ng test --watch=false --browsers=ChromeHeadless
