name: Test

on:
  pull_request:
    branches: 
      - develop
jobs:
  unittest:
    name: Run unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          npm ci
          npm test
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: |
          npm ci
          npm run build --configuration=essprod
